context:
  action: on_status
  bap_id: fis.test.bap.io
  bap_uri: https://fis.test.bap.io/
  bpp_id: fis.test.bpp.io
  bpp_uri: https://fis.test.bpp.io/
  domain: ONDC:FIS13
  location:
    country:
      code: IND
    city:
      code: '*'
  message_id: bfa97ac4-0c6f-4fa7-a287-be61f2aa1c1d
  timestamp: "2023-07-22T15:03:18.179Z"
  transaction_id: a4db048b-d07c-40e0-9c0b-b7f006c4df74
  ttl: PT24H
  version: 2.0.0
message:
  order:
    # fulfillments:
    #   - state:
    #       descriptor:
    #         code: PROCESSING
    #     id: F1
    items:
      - id: CHILD_ITEM_CI1
        parent_item_id: I1
        category_ids:
          - C3
          - C4
          - C5
          - C6  
        descriptor:
          name: 2-Wheeler 3rd Party Motor Insurance
          short_desc: 2-Wheeler 3rd Party Motor Insurance by ABC Insurance Provider
        price:
          value: "11531"
          currency: INR
        tags:
          - descriptor:
              code: GENERAL_INFO
            list:
              - descriptor:
                  code: PERSONAL_ACCIDENT_COVER
                value: "10000000"
              - descriptor:
                  code: DEPRECIATION_COVER
                value: Yes
              - descriptor:
                  code: ROAD_SIDE_ASSISTANCE
                value: "25000"
              - descriptor:
                  code: CONSUMABLES_COVER
                value: No
              - descriptor:
                  code: ELECTRICAL_ACCESSORIES_COVER
                value: "0.8"
              - descriptor:
                  code: NON_ELECTRICAL_ACCESSORIES_COVER
                value: "2"
              - descriptor:
                  code: ENGINE_COVER
                value: "5"
              - descriptor:
                  code: EXTERNAL_CNG_OR_LPG_COVER
                value: Yes
              - descriptor:
                  code: KEY_COVER
                value: No
              - descriptor:
                  code: PERSONAL_BAGGAGE_COVER
                value: "50"
              - descriptor:
                  code: TYRE_COVER
                value: "50"
              - descriptor:
                  code: RETURN_TO_INVOICE
                value: "50"
              - descriptor:
                  code: PER_DAY_CASH
                value: "50"
              - descriptor:
                  code: MANUAL_REVIEW
                  name: Manual Review
                  short_desc: Describes manual review value
                value: 'true'
              - descriptor:
                  code: IDV_VALUE
                  name: "IDV value"
                  short_desc: Describes the IDV value
                value: '300000'  
        
          - descriptor:
              code: VAHAN_DETAILS
              name: Vahan Details
            list:
              - descriptor:
                  code: MODEL
                value: X100
              - descriptor:
                  code: MAKE
                value: BMX
              - descriptor:
                  code: FUEL_TYPE
                value: Petrol
              - descriptor:
                  code: VARIANT
                value: ZX
              - descriptor:
                  code: REGISTERED_CITY
                value: Bangalore
              - descriptor:
                  code: REGISTERED_DATE
                value: "2022-01-13"
              - descriptor:
                  code: CHASSIS_NUMBER
                value: nvuwi3n23io90
              - descriptor:
                  code: ENGINE_NUMBER
                value: 98vd98e32
              - descriptor:
                  code: PREVIOUS_POLICY_NUMBER
                value: f5f90d6e8f924
              - descriptor:
                  code: PREVIOUS_INSURER
                value: XYZ
              - descriptor:
                  code: PREVIOUS_POLICY_END_DATE
                value: "2022-01-02"
        # fulfillment_ids: 
        #   - F1
        time:
          duration: P1Y
          label: TENURE
        xinput:
          form:
            id: F05
          form_response:
            status: APPROVED
            submission_id: 73ef9742-c17d-4c4e-92e3-b057960863af
        add_ons:
          - id: A1
            price: 
              currency: INR
              value: '900' 
            quantity:  
              selected:
                count: 1
            descriptor:
              name: Consumables Cover
              code: CONSUMABLES_COVER
    provider:
      descriptor:
        long_desc: ABC Insurance Ltd. Deals in multiple Insurance Services like Health,
          Motor, Marine etc
        name: ABC Insurance Ltd.
        short_desc: "ABC Insurance Ltd. India "
        images:
          - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
      id: P1
    quote:
      id: Q1
      price:
        currency: INR
        value: "12505"
      # breakup:
      #   - price:
      #       value: "3634"
      #       currency: INR
      #     title: Basic OD
      #   - price:
      #       value: "7897"
      #       currency: INR
      #     title: Basic TP
      #   - title: "Add On(old)
      #     item:
      #       id: A1
      #     price:
      #       value: "974"
      #       currency: INR
      breakup:
        - price:
            value: "11531"
            currency: INR
          title: BASE_PRICE
        - price:
            value: "50"
            currency: INR
          title: CONVIENCE_FEE
        - price:
            value: "30"
            currency: INR
          title: TAX 
        - price:
            value: "20"
            currency: INR
          title: PROCESSING_FEE   
        - title: "ADD_ONS"
          item:
            id: A1
          price:
            value: "900"
            currency: INR
      ttl: PT15D 