summary: Form Status for application/html
details:
  - description: Detailed process form responses flows in case if mime type is application/html
    mermaid: >-
      sequenceDiagram
        participant Buyer Platform (BAP)
        participant Insurer Platform (BPP)
        participant Insurer Form Service
        Insurer Platform (BPP)->>Buyer Platform (BAP):on_select
        Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK 
        Buyer Platform (BAP)->>Insurer Form Service: Get Form
        Insurer Form Service-->>Buyer Platform (BAP): Form Received
        Buyer Platform (BAP)->>Insurer Form Service: Form Submission
        Insurer Form Service-->>Buyer Platform (BAP): Submission ID 
        Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
        Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
        Buyer Platform (BAP)->>Insurer Platform (BPP): status
        Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
        Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
        Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK       
references: if any
steps:
  - summary: Insurer returns the response to selected marine insurance plan
    api: on_select
    details:
      - description: Insurer responds to the buyer app requests by sending the additional info form.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            participant Insurer Form Service
            rect rgb(191, 223, 255)
            Insurer Platform (BPP)->>Buyer Platform (BAP):on_select
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK 
            end
            Buyer Platform (BAP)->>Insurer Form Service: Get Form
            Insurer Form Service-->>Buyer Platform (BAP): Form Received
            Buyer Platform (BAP)->>Insurer Form Service: Form Submission
            Insurer Form Service-->>Buyer Platform (BAP): Submission ID 
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
    reference: if any
    example:
      value:
        $ref: "../../examples/marine-insurance/on_select/on_select-request-aadhar-kyc.yaml"  
  - summary: Buyer app fetches the additional information based form
    api: form
    details:    
      - description: Buyer app fetches the additional information details form from the insurer using the link provided in the previous step.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            participant Insurer Form Service
            Insurer Platform (BPP)->>Buyer Platform (BAP):on_select
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK 
            rect rgb(191, 223, 255)
            Buyer Platform (BAP)->>Insurer Form Service: Get Form
            Insurer Form Service-->>Buyer Platform (BAP): Form Received
            Buyer Platform (BAP)->>Insurer Form Service: Form Submission
            Insurer Form Service-->>Buyer Platform (BAP): Submission ID 
            end
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
    reference: if any        
    example:
      value:
        $ref: "../../examples/marine-insurance/forms/application-html.html"       
  
  - summary: Insurer provides the buyer with latest update of form status
    api: on_status
    details:
      - description: Insurer provides the buyer with latest update of form status from unsolicited call.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            participant Insurer Form Service
            Insurer Platform (BPP)->>Buyer Platform (BAP):on_select
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK 
            Buyer Platform (BAP)->>Insurer Form Service: Get Form
            Insurer Form Service-->>Buyer Platform (BAP): Form Received
            Buyer Platform (BAP)->>Insurer Form Service: Form Submission
            Insurer Form Service-->>Buyer Platform (BAP): Submission ID 
            rect rgb(191, 223, 255)
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
            end
    reference: if any
    example:
      value: 
        $ref: "../../examples/marine-insurance/on_status/on_status_aadhaar_success.yaml"
  - summary: Buyer app request the latest form status updates
    api: status
    details:
      - description: Buyer app request the latest form status updates with the form id.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            rect rgb(191, 223, 255)
            Buyer Platform (BAP)->>Insurer Platform (BPP): status
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
            end
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
            Buyer Platform (BAP)->>Insurer Platform (BPP): init
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
    reference: if any
    example:
      value: 
        $ref: "../../examples/marine-insurance/status/status-request-ref.yaml"      
  - summary: Insurer provides the buyer with latest update of form status (Form Processing)
    api: on_status
    details:
      - description: Insurer provides the buyer with latest update of the form status of form processing.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            Buyer Platform (BAP)->>Insurer Platform (BPP): status
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
            rect rgb(191, 223, 255)
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
            end
            Buyer Platform (BAP)->>Insurer Platform (BPP): init
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
                
    reference: if any
    example:
      value: 
        $ref: "../../examples/marine-insurance/on_status/on_status_aadhaar_pending.yaml"
  
  - summary: Buyer app initiates the marine insurace request
    api: init
    details:
      - description: Buyer app initiates purchase of a specific marine insurance plan that suits their needs and links the EKYC submission details with it.
        mermaid: >-
          sequenceDiagram
            participant Buyer Platform (BAP)
            participant Insurer Platform (BPP)
            Buyer Platform (BAP)->>Insurer Platform (BPP): status
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
            Insurer Platform (BPP)->> Buyer Platform (BAP): on_status
            Buyer Platform (BAP)-->>Insurer Platform (BPP): ACK
            rect rgb(191, 223, 255)
            Buyer Platform (BAP)->>Insurer Platform (BPP): init
            Insurer Platform (BPP)-->>Buyer Platform (BAP): ACK
            end
    reference: if any
    example: 
      value:
        $ref: "../../examples/marine-insurance/init/init-request.yaml"