summary: Form Status for application/html
details:
  - description: Detailed process form responses flows in case if mime type is application/html.
    mermaid: >-
      sequenceDiagram
        participant Borrower Platform (BAP)
        participant Lender Platform(BPP)
        participant Lender Form Service
        Lender Platform(BPP)->>Borrower Platform (BAP):on_select
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
        Borrower Platform (BAP)->>Lender Form Service: Get Form
        Lender Form Service-->>Borrower Platform (BAP): Form Received
        Borrower Platform (BAP)->>Lender Form Service: Form Submission
        Lender Form Service-->>Borrower Platform (BAP): Submission ID 
        Borrower Platform (BAP)->>Lender Platform(BPP): status
        Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
        Lender Platform(BPP)->> Borrower Platform (BAP): on_status
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
        Lender Platform(BPP)->> Borrower Platform (BAP): on_status(unsolicated)
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
references: if any
steps:
  - summary: Seller app returns the response to selected mutual fund with xinput forms.
    api: on_select
    details:
      - description: Seller app returns the response to selected mutual fund with payment information forms.
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            rect rgb(191, 223, 255)
            Lender Platform(BPP)->>Borrower Platform (BAP):on_select
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
            end
            Borrower Platform (BAP)->>Lender Form Service: Get Form
            Lender Form Service-->>Borrower Platform (BAP): Form Received
            Borrower Platform (BAP)->>Lender Form Service: Form Submission
            Lender Form Service-->>Borrower Platform (BAP): Submission ID 
    reference: if any
    example:
      value: 
        $ref: "../../examples/mutual-funds/on_select/on_select-request-payment_1.2.yaml"    
  - summary: Get the Payment Info form(Redirection)
    api: form
    details:
      - description: Provider platform sends the Payment Info From.
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            Lender Platform(BPP)->>Borrower Platform (BAP):on_select
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Form Service: Get Form
            Lender Form Service-->>Borrower Platform (BAP): Form Received
            Borrower Platform (BAP)->>Lender Form Service: Form Submission
            Lender Form Service-->>Borrower Platform (BAP): Submission ID 
            end
    reference: if any
    example:
      value: 
        $ref: ../../examples/mutual-funds/forms/mutual-funds-payment-info.html  
  - summary: The borrower seeks the most recent form status update.
    api: status
    details:
      - description: Borrower platform request the latest form status updates with the formID
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            end
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
    reference: if any
    example:
      value: 
        $ref: "../../examples/mutual-funds/status/status-request-payment.yaml"      
  - summary: The lender shares the latest form status with the borrower.
    api: on_status
    details:
      - description: The lender platform updates the borrower with the most recent status of the mutual-fund application including installment details.
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            rect rgb(191, 223, 255)
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            end
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
    reference: if any
    example:
      value: 
        $ref: "../../examples/mutual-funds/on_status/on_status-request-payment-pending.yaml"      
  - summary: The lender shares the latest form status with the borrower.
    api: on_status
    details:
      - description: The lender platform updates the borrower with the most recent status of the mutual-fund application including installment details.
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)

            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK            
            rect rgb(191, 223, 255) 
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            end
    reference: if any
    example:
      value: 
        $ref: "../../examples/mutual-funds/on_status/on_status-request-payment-approved.yaml" 
  # - summary: The borrower initiates the mutual-fund request by filling the form
  #   api: init
  #   details:
  #     - description: The borrower platform initiates the mutual-fund request by filling the form such as KYC detals, bank details and e-madate.
  #       mermaid: >-
  #         sequenceDiagram
  #           title  Selection
  #           participant Borrower Platform (BAP)
  #           participant Lender Platform(BPP)
  #           Lender Platform(BPP)->> Borrower Platform (BAP): on_status
  #           Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
  #           rect rgb(191, 223, 255)
  #           Borrower Platform (BAP)->>Lender Platform(BPP): init
  #           Lender Platform (BPP)-->>Borrower Platform(BAP): ACK
  #           end
  #   reference: if any
  #   example: 
  #     value:
  #       $ref: "../../examples/mutual-funds/init/init-request-payment-info-1.2.yaml"
