context:
  action: on_select
  bap_id: fis.test.bap.io
  bap_uri: https://fis.test.bap.io/
  bpp_id: fis.test.bpp.io
  bpp_uri: https://fis.test.bpp.io/
  domain: ONDC:FIS13
  location:
    country:
      code: IND
    city:
      code: "*"
  message_id: 519da438-68dc-4f2c-bd10-79c0f88c3924
  timestamp: "2023-07-24T05:40:26.618Z"
  transaction_id: c04a04ee-d892-400f-bbe6-479a43b4448a
  ttl: PT24H
  version: 2.0.0
message:
  order:
    items:
      - category_ids:
          - C1
        descriptor:
          name: ABC Marine Insurance Policy
          short_desc: ABC Marine Insurance Class A
        id: I1
        tags:
          - descriptor:
              name: Policy Details
              code: POLICY_DETAILS
            list:
              - descriptor:
                  name: Commodity type
                  code: COMMODITY_TYPE
                value: FOOD
              - descriptor:
                  name: Sum insured
                  code: SUM_INSURED
                value: "100000"
              - descriptor:
                  name: Mode of conveyance
                  code: MODE_OF_CONVEYANCE
                value: Cargo
              - descriptor:
                  name: Basis of valuation
                  code: BASIS_OF_VALUATION
                value: "5"
        time:
          duration: P1Y
          label: TENURE
        xinput:
          head:
            descriptor:
              name: Customer Information
            index:
              min: 0
              cur: 2
              max: 2
            headings:
              - PED Details
              - PAN & DOB Details
              - EKYC
          form:
            id: FO4
            mime_type: application/html
            url: https://fis.test.bpp.io/form/ekyc_dtls?formid=FO4
            resubmit: true
            multiple_sumbissions: false
          required: true
        add_ons:
          - id: A1
            quantity:
              selected:
                count: 1
            descriptor:
              name: No Claim Bonus
              code: NO_CLAIM_BONUS
            price:
              value: "100"
              currency: "INR"
    provider:
      descriptor:
        long_desc:
          ABC Insurance Ltd. Deals in multiple Insurance Services like Health,
          Motor, Marine etc
        name: ABC Insurance Ltd.
        short_desc: "ABC Insurance Ltd. India "
        images:
          - url: https://www.abcinsurance.com/content/dam/abc/india/assets/images/header/logo.png
            size_type: xs
      id: P1
    quote:
      id: PROPOSAL_ID
      breakup:
        - price:
            value: "900"
            currency: INR
          # title: Base Price
          title: BASE_PRICE
        - price:
            value: "50"
            currency: INR
          # title: Convience Fee
          title: CONVIENCE_FEE
        - price:
            value: "40"
            currency: INR
          # title: Tax
          title: TAX
        - price:
            value: "10"
            currency: INR
          # title: Processing Fee
          title: PROCESSING_FEE
        - title: ADD_ONS
          item:
            id: "I1"
            add_ons:
              - id: "A1"
          price:
            value: "100"
            currency: INR
      price:
        currency: INR
        value: "1100"
